# Generated by Django 2.1.1 on 2019-07-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20190628_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newassetapprovalzone',
            name='date',
            field=models.DateTimeField(auto_now=True, verbose_name='汇报日期'),
        ),
    ]
